services:
  video-editor-dev:
    build:
      context: .
      target: dev
    container_name: video-editor-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - video_editor_node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"

  video-editor-prod:
    build:
      context: .
      target: prod
    container_name: video-editor-prod
    ports:
      - "8080:80"
    profiles:
      - prod

volumes:
  video_editor_node_modules:
